In [7]:
import numpy as np
import torch
import tensorflow as tf

In [13]:
tf.device('cpu')

In [5]:
A = np.array([[56, 0, 4.4, 68],
              [1.2, 104, 52, 8],
              [1.8, 135, 99, .9]])
A

array([[ 56. ,   0. ,   4.4,  68. ],
       [  1.2, 104. ,  52. ,   8. ],
       [  1.8, 135. ,  99. ,   0.9]])

In [17]:
tf_A = tf.convert_to_tensor(A)
torch_A = torch.tensor(A)

## 1. With Numpy

In [6]:
cal = A.sum(axis=0)
cal

array([ 59. , 239. , 155.4,  76.9])

In [21]:
percentage = 100 * A / cal # broadcasting -> (3, 4) / (1, 4) => (3, 4) / (3, 4)
percentage

array([[94.91525424,  0.        ,  2.83140283, 88.42652796],
       [ 2.03389831, 43.51464435, 33.46203346, 10.40312094],
       [ 3.05084746, 56.48535565, 63.70656371,  1.17035111]])

## 2. With Pytorch

In [28]:
cal = torch.sum(torch_A, axis=0)
cal

tensor([ 59.0000, 239.0000, 155.4000,  76.9000], dtype=torch.float64)

In [29]:
percentage = 100 * torch_A / cal
percentage

tensor([[94.9153,  0.0000,  2.8314, 88.4265],
        [ 2.0339, 43.5146, 33.4620, 10.4031],
        [ 3.0508, 56.4854, 63.7066,  1.1704]], dtype=torch.float64)

## 3. With Tensorflow

In [30]:
cal = tf.math.reduce_sum(tf_A, axis=0)
cal

<tf.Tensor: shape=(4,), dtype=float64, numpy=array([ 59. , 239. , 155.4,  76.9])>

In [31]:
percentage = 100 * tf_A / cal
percentage

<tf.Tensor: shape=(3, 4), dtype=float64, numpy=
array([[94.91525424,  0.        ,  2.83140283, 88.42652796],
       [ 2.03389831, 43.51464435, 33.46203346, 10.40312094],
       [ 3.05084746, 56.48535565, 63.70656371,  1.17035111]])>

![](img/broadcasting.jpg)