In [3]:
import numpy as np
import tensorflow as tf
import torch

In [4]:
a = np.random.randn(5)
a

array([ 1.86842831, -2.15585322,  1.09802387, -0.51125732,  0.74555755])

In [5]:
a.shape

(5,)

In [6]:
a.T

array([ 1.86842831, -2.15585322,  1.09802387, -0.51125732,  0.74555755])

In [7]:
a.T.shape

(5,)

`a is neither a row vector or a cloumn vector, it is a one ranked array`

In [8]:
np.dot(a, a.T)

10.161623981847924

## Good practice

In [9]:
a = np.random.randn(5, 1)
a

array([[0.17966741],
       [2.19330527],
       [0.84296843],
       [0.94126048],
       [2.5912626 ]])

In [10]:
a.T

array([[0.17966741, 2.19330527, 0.84296843, 0.94126048, 2.5912626 ]])

In [11]:
np.dot(a, a.T)

array([[0.03228038, 0.39406547, 0.15145395, 0.16911383, 0.46556543],
       [0.39406547, 4.81058801, 1.8488871 , 2.06447157, 5.68342991],
       [0.15145395, 1.8488871 , 0.71059577, 0.79345287, 2.18435256],
       [0.16911383, 2.06447157, 0.79345287, 0.88597129, 2.43905307],
       [0.46556543, 5.68342991, 2.18435256, 2.43905307, 6.71464184]])

## In Pytorch

In [13]:
a = torch.randn(5, 1)
a

tensor([[-0.9169],
        [ 1.1065],
        [ 1.4160],
        [ 0.1194],
        [ 0.4314]])

In [16]:
torch.mm(a, a.T)

tensor([[ 0.8407, -1.0145, -1.2983, -0.1095, -0.3955],
        [-1.0145,  1.2244,  1.5668,  0.1321,  0.4773],
        [-1.2983,  1.5668,  2.0050,  0.1691,  0.6108],
        [-0.1095,  0.1321,  0.1691,  0.0143,  0.0515],
        [-0.3955,  0.4773,  0.6108,  0.0515,  0.1861]])

## In TF

In [20]:
a = tf.random.uniform((5, 1))
a

<tf.Tensor: shape=(5, 1), dtype=float32, numpy=
array([[0.31313443],
       [0.27038956],
       [0.6768497 ],
       [0.18750107],
       [0.8662138 ]], dtype=float32)>

In [24]:
tf.matmul(a, a, transpose_b=True)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[0.09811455, 0.08473182, 0.21198249, 0.05873108, 0.27132535],
       [0.08473182, 0.07317448, 0.18306828, 0.05072021, 0.23431683],
       [0.21198249, 0.18306828, 0.45800114, 0.12689209, 0.586215  ],
       [0.05873108, 0.05072021, 0.12689209, 0.03515625, 0.16241455],
       [0.27132535, 0.23431683, 0.586215  , 0.16241455, 0.7503214 ]],
      dtype=float32)>