In [1]:
import numpy as np
import torch
import tensorflow as tf

## 1. Sigmoid function

In [2]:
def sigmoid_np(x):
    """
    Compute sigmoid of x.

    Arguments:
    x -- A scalar

    Return:
    s -- sigmoid(x)
    """
  
    return 1 / (1 + np.exp(-x))

In [3]:
def sigmoid_torch(x):
    return 1 / (1 + torch.exp(-x))

@tf.function
def sigmoid_tf(x):
    return 1 / (1 + tf.math.exp(-x))

## 2. Sigmoid derivate

In [4]:
def sigmoid_derivative_np(x):
    """
    Compute the gradient (also called the slope or derivative) of the sigmoid function with respect to its input x.
    You can store the output of the sigmoid function into variables and then use it to calculate the gradient.
    
    Arguments:
    x -- A scalar or numpy array

    Return:
    ds -- Your computed gradient.
    """
    
    return sigmoid_np(x) * (1 - sigmoid_np(x))

In [5]:
def sigmoid_derivate_torch(x):
    return sigmoid_torch(x) * (1 - sigmoid_torch(x))

@tf.function
def sigmoid_derivate_tf(x):
    return sigmoid_tf(x) * (1 - sigmoid_tf(x))

## 3. image2vector

In [6]:
def image2vector(image):
    """
    Argument:
    image -- a numpy array of shape (length, height, depth)
    
    Returns:
    v -- a vector of shape (length*height*depth, 1)
    """
        
    return image.reshape(-1, 1)

## 4. Normalised rows

In [7]:
def normalize_rows_np(x):
    """
    Implement a function that normalizes each row of the matrix x (to have unit length).
    
    Argument:
    x -- A numpy matrix of shape (n, m)
    
    Returns:
    x -- The normalized (by row) numpy matrix. You are allowed to modify x.
    """

    return x / np.linalg.norm(x, keepdims=True, axis=1)

## 5. Softmax

In [8]:
def softmax_np(x):
    """Calculates the softmax for each row of the input x.

    Your code should work for a row vector and also for matrices of shape (m,n).

    Argument:
    x -- A numpy matrix of shape (m,n)

    Returns:
    s -- A numpy matrix equal to the softmax of x, of shape (m,n)
    """
    
    x_exp = np.exp(x)
    s_sum = np.sum(x_exp, axis=1, keepdims=True)
    s = x_exp / s_sum
    
    return s

In [9]:
def softmax_torch(x):
    x_exp = torch.exp(x)
    s_sum = torch.sum(x_exp, axis=1, keepdims=True)
    s = x_exp / s_sum
    return s

# torch.nn.Softmax

In [10]:
@tf.function
def softmax_tf(x):
    x_exp = tf.math.exp(x)
    s_sum = tf.math.reduce_sum(x_exp, axis=1, keepdims=True)
    s = x_exp / s_sum
    return s

# tf.nn.softmax()

## 6. L1 Loss

$$\begin{align*} & L_1(\hat{y}, y) = \sum_{i=0}^{m-1}|y^{(i)} - \hat{y}^{(i)}| \end{align*}$$

In [11]:
def L1_np(yhat, y):
    """
    Arguments:
    yhat -- vector of size m (predicted labels)
    y -- vector of size m (true labels)
    
    Returns:
    loss -- the value of the L1 loss function defined above
    """

    loss = np.sum(np.abs(y - yhat))

    return loss

In [12]:
def L1_torch(yhat, y):
    return torch.sum(torch.abs(y - yhat))

In [46]:
def L1_tf(yhat, y):
    return tf.math.reduce_sum(tf.math.abs(y - yhat))

## 7. L2 Loss

$$\begin{align*} & L_2(\hat{y},y) = \sum_{i=0}^{m-1}(y^{(i)} - \hat{y}^{(i)})^2 \end{align*}$$

In [14]:
def L2_np(yhat, y):
    """
    Arguments:
    yhat -- vector of size m (predicted labels)
    y -- vector of size m (true labels)
    
    Returns:
    loss -- the value of the L2 loss function defined above
    """
    
    loss = np.sum(np.square(y - yhat))
    
    return loss

In [15]:
def L2_torch(yhat, y):
    return torch.sum(torch.square(y - yhat))

In [50]:
def L2_tf(yhat, y):
    return tf.math.reduce_sum(tf.math.square(y - yhat))

## 8. Test

In [19]:
x = np.random.rand(3, 3)
b = np.random.rand(3, 3)
x_torch = torch.Tensor(x)
b_torch = torch.Tensor(b)
x_tf = tf.convert_to_tensor(x)
b_tf = tf.convert_to_tensor(b)

### 8.1 Sigmoid

In [20]:
sigmoid_np(x)

array([[0.72552503, 0.51730211, 0.51829266],
       [0.71412494, 0.50776203, 0.52976755],
       [0.6399525 , 0.73006214, 0.61462965]])

In [21]:
sigmoid_torch(x_torch)

tensor([[0.7255, 0.5173, 0.5183],
        [0.7141, 0.5078, 0.5298],
        [0.6400, 0.7301, 0.6146]])

In [22]:
sigmoid_tf(x_tf)

<tf.Tensor: shape=(3, 3), dtype=float64, numpy=
array([[0.72552503, 0.51730211, 0.51829266],
       [0.71412494, 0.50776203, 0.52976755],
       [0.6399525 , 0.73006214, 0.61462965]])>

## 8.2 Sigmoid derivate

In [23]:
sigmoid_derivative_np(x)

array([[0.19913846, 0.24970064, 0.24966538],
       [0.20415051, 0.24993975, 0.24911389],
       [0.2304133 , 0.19707141, 0.23686004]])

In [24]:
sigmoid_derivate_torch(x_torch)

tensor([[0.1991, 0.2497, 0.2497],
        [0.2042, 0.2499, 0.2491],
        [0.2304, 0.1971, 0.2369]])

In [25]:
sigmoid_derivate_tf(x_tf)

<tf.Tensor: shape=(3, 3), dtype=float64, numpy=
array([[0.19913846, 0.24970064, 0.24966538],
       [0.20415051, 0.24993975, 0.24911389],
       [0.2304133 , 0.19707141, 0.23686004]])>

### 8.3 Softmax

In [26]:
softmax_np(x)

array([[0.55173089, 0.22368996, 0.22457915],
       [0.53649841, 0.22154177, 0.24195982],
       [0.29248776, 0.44505717, 0.26245507]])

In [27]:
softmax_torch(x_torch)

tensor([[0.5517, 0.2237, 0.2246],
        [0.5365, 0.2215, 0.2420],
        [0.2925, 0.4451, 0.2625]])

In [35]:
s = torch.nn.Softmax(dim=1)
s(x_torch)

tensor([[0.5517, 0.2237, 0.2246],
        [0.5365, 0.2215, 0.2420],
        [0.2925, 0.4451, 0.2625]])

In [28]:
softmax_tf(x_tf)

<tf.Tensor: shape=(3, 3), dtype=float64, numpy=
array([[0.55173089, 0.22368996, 0.22457915],
       [0.53649841, 0.22154177, 0.24195982],
       [0.29248776, 0.44505717, 0.26245507]])>

In [37]:
tf.nn.softmax(x_tf)

<tf.Tensor: shape=(3, 3), dtype=float64, numpy=
array([[0.55173089, 0.22368996, 0.22457915],
       [0.53649841, 0.22154177, 0.24195982],
       [0.29248776, 0.44505717, 0.26245507]])>

### 8.4 L1 Loss

In [39]:
L1_np(x, b)

3.760220120014178

In [40]:
L1_torch(x_torch, b_torch)

tensor(3.7602)

In [47]:
L1_tf(x_tf, b_tf)

<tf.Tensor: shape=(), dtype=float64, numpy=3.760220120014178>

### 8.5 L2 Loss

In [48]:
L2_np(x, b)

2.295049316056502

In [49]:
L2_torch(x_torch, b_torch)

tensor(2.2950)

In [51]:
L2_tf(x_tf, b_tf)

<tf.Tensor: shape=(), dtype=float64, numpy=2.295049316056502>